### ISSUE TITLE
Issue with websockets receiving bad status v1.0.4

### ISSUE THREAD

**Issue by JordanFaust** [percona/qan-agent#30]
I have setup and deployed the pmm-server as a Marathon app within Mesos and have successfully setup the linux:metrics and mysql:metrics monitoring on the mysql nodes I am interested in monitoring. I have not been able to successfully get mysql:queries to return anything to the server. Whenever I attempt to view any of the registered nodes I get an error message saying:

"QAN API error: "MySQL Query Analytics configuration not found".
Check the /var/log/qan-api.log file in docker container for more information."

Clicking into the server info tab also reports that no agents are connected.

I setup the pmm-client on the mysql nodes with the following steps:

1) sudo pmm-client config --server pmm.dcos.us.monitoring.net --client-address 10.190.110.180
2) sudo pmm-admin add mysql --user abc --password 123 --query-source=perfschema

NOTE: I have had to manually specify the client-address as without it the pmm-client was assigning the client-address to something other then the nodes ip address and resulted in errors attempting to listen on a local ports (42000, 42001, etc).

After the above the output of the version, config, list and check-network commands are as follows:

```
sudo pmm-admin --version
1.0.4
```

```
sudo pmm-admin config
OK, PMM server is alive.

PMM Server | pmm.dcos.us.monitoring.net
Client Name | node1.northamerica.company.net
Client Address | 10.190.110.180
```

```
sudo pmm-admin list
pmm-admin 1.0.4

PMM Server | pmm.dcos.us.monitoring.net
Client Name | node1.northamerica.company.net
Client Address | 10.190.110.180
Service manager | unix-systemv

-------------- --------------------------------------- ------------ -------- ----------------------------------------- ------------------------
SERVICE TYPE NAME CLIENT PORT RUNNING DATA SOURCE OPTIONS
-------------- --------------------------------------- ------------ -------- ----------------------------------------- ------------------------
linux:metrics node1.northamerica.company.net 42000 YES -
mysql:queries node1.northamerica.company.net 42001 YES root:***@unix(/var/lib/mysql/mysql.sock) query_source=perfschema
mysql:metrics node1.northamerica.company.net 42002 YES root:***@unix(/var/lib/mysql/mysql.sock)
```

```
sudo pmm-admin check-network

PMM Network Status

Server | pmm.dcos.us.monitoring.net
Client | 10.190.110.180

* Client --> Server
--------------- -------------
SERVER SERVICE CONNECTIVITY
--------------- -------------
Consul API 🙂
QAN API 🙂
Prometheus API 🙂

Connection duration | 8.010026ms
Request duration | 9.588105ms
Full round trip | 17.598131ms

* Client <-- Server
------- --------------------------------------- ---------------------- -------------
METRIC NAME PROMETHEUS ENDPOINT REMOTE STATE
------- --------------------------------------- ---------------------- -------------
linux node1.northamerica.company.net 10.190.110.180:42000 🙂
mysql node1.northamerica.company.net 10.190.110.180:42002 🙂
```

Everything reports back fine from the network check however none of the registered nodes have an agent running.

Looking into the log file for the mysql queries agent in /var/log/pmm-mysql-queries-42001.log has the following:

```
# Version: percona-qan-agent 1.0.4
# Basedir: /usr/local/percona/qan-agent
# Listen: 127.0.0.1:42001
# PID: 30186
# API: pmm.dcos.us.monitoring.net/qan-api
# UUID: 2abee053593a468954864c50bf349c77
2016/10/12 11:48:43.345091 main.go:160: Starting agent...
2016/10/12 11:48:43.347031 main.go:338: Agent is ready
2016/10/12 11:48:43.379967 main.go:202: API is ready
2016/10/12 11:48:44.366158 WARNING agent-ws bad status
2016/10/12 11:48:44.374480 WARNING log-ws bad status
2016/10/12 11:48:47.378230 WARNING agent-ws bad status
2016/10/12 11:48:47.389480 WARNING log-ws bad status
2016/10/12 11:48:54.395134 WARNING agent-ws bad status
2016/10/12 11:48:54.407000 WARNING log-ws bad status
2016/10/12 11:49:09.410770 WARNING agent-ws bad status
2016/10/12 11:49:09.419484 WARNING log-ws bad status
2016/10/12 11:49:40.426126 WARNING agent-ws bad status
2016/10/12 11:49:40.430234 WARNING log-ws bad status
2016/10/12 11:49:46.363162 WARNING data-sender Cannot connect to API: bad status
2016/10/12 11:49:49.379162 WARNING data-sender Cannot connect to API: bad status
2016/10/12 11:49:52.399097 WARNING data-sender Cannot connect to API: bad status
```

I have not been able to figure out what the problem is with connecting to the server.

From the node I can hit the qan-api just fine:

```
curl pmm.dcos.us.monitoring.net/qan-api
{"Links":{"agents":"http://pmm.dcos.us.monitoring.net/qan-api/agents","instances":"http://pmm.dcos.us.monitoring.net/qan-api/instances"}}
```

I also get the following error when attempting to hit the agents endpoint of the qan-api:

```
curl pmm.dcos.us.monitoring.net/qan-api/agents
{
"Error": "Agent.List: ah.GetAll: sql: Scan error on column index 5: unsupported Scan, storing driver.Value type into type *time.Time"
}
```

Any help in resolving this would be greatly appreciated. Both the client and the server are fresh installs with both of them being installed yesterday/today.

I have asked this question on the forum but feel that debugging this is going to be more technical then the forums appear to dive into. 

The suggestion on the forum was to attempt to add and remove the mysql:queries monitoring which I have done multiple times on multiple different machines and nothing has changed. 

This deployment is running as a Marathon app within Mesos and we are using Marathon LB for service discovery and getting the nice url I have configured. If there are additional ports that need to be accessed by the agent I will need to open those up within Marathon but could not find anything documented and have been struggling to understand this project enough to know what to test.

**Comment by JordanFaust** [comment]
Tested this a little more and I was able to use a Chrome extension for websockets to connect to the server. So the server as it is currently deployed at least accepts the connection. Attempting to figure out how to best test this on the node I have mysql running on.

**Comment by roman-vynar** [comment]
Tomorrow we will have 1.0.5. You may want to try to upgrade and re-add mysql:queries using the new client and docker image version.

**Comment by JordanFaust** [comment]
Still having the exact same issue with the new version. Create a new deployment using the 1.0.5 version of the pmm-server and installed the pmm-client on a fresh node.

This time the mysql:queries portion failed with the following error:

```
09:58:22 $ sudo pmm-admin add mysql:queries --password phappinfraroot --query-source perfschema --create-user --force
Error adding MySQL queries: timeout 10s waiting on agent to connect to API.
```

Looking at the logs they are the exact same as before:
```
# Version: percona-qan-agent 1.0.5
# Basedir: /usr/local/percona/qan-agent
# Listen:  127.0.0.1:42001
# PID:     22134
# API:     pmm-v1.0.5.dcos.us.monitoring.net/qan-api
# UUID:    42bcfb8c37904b8d4a1fc6d837b100b7
2016/10/14 09:58:46.683657 main.go:165: Starting agent...
2016/10/14 09:58:46.684977 main.go:343: Agent is ready
2016/10/14 09:58:46.722351 main.go:207: API is ready
2016/10/14 09:58:47.701950 WARNING log-ws bad status
2016/10/14 09:58:47.703493 WARNING agent-ws bad status
2016/10/14 09:58:50.716747 WARNING log-ws bad status
2016/10/14 09:58:50.718247 WARNING agent-ws bad status
2016/10/14 09:58:57.733569 WARNING agent-ws bad status
2016/10/14 09:58:57.737430 WARNING log-ws bad status
2016/10/14 09:59:12.748830 WARNING agent-ws bad status
2016/10/14 09:59:12.750109 WARNING log-ws bad status
2016/10/14 09:59:43.763582 WARNING log-ws bad status
2016/10/14 09:59:43.767224 WARNING agent-ws bad status
2016/10/14 09:59:49.696973 WARNING data-sender Cannot connect to API:  bad status
2016/10/14 09:59:52.710759 WARNING data-sender Cannot connect to API:  bad status
2016/10/14 09:59:55.726196 WARNING data-sender Cannot connect to API:  bad status
2016/10/14 10:00:43.781682 WARNING agent-ws bad status
2016/10/14 10:00:43.784763 WARNING log-ws bad status
```

I can connect to the WebSockets endpoints from my browser and I am still working on find a good way to test and verify that from the mysql node. What additional information will help in solving this problem?

**Comment by roman-vynar** [comment]
So now it is correctly complains on the timeout. Previously, due to the bug, it was silently adding despite the timeout. Are client and server hosted in the same network? Looks like pmm-server performs really slow so we have this timeout.

**Comment by JordanFaust** [comment]
Everything can communicate just fine this appears to be an issue with how the websockets are attempting to connect. What ports is the qan-agent attempting to connect to the server over? Is everything communicating with the server over port 80 or are there other ports that I need to know about?

**Comment by roman-vynar** [comment]
All the communication is done on the same port, i.e. 80 or 443 (or how they are remapped on container run). This also applies to qan-agent websocket connection.

You said you are running container on Mesos. Thus, I assume there is some proxy logic behind this. 

I can say for sure, that the following directives are required on nginx that we employ on container to make WS connection successful:
http section
```
map $http_upgrade $connection_upgrade {
	default upgrade;
	'' close;
}
```
location section
```
proxy_set_header	Host $http_host;
proxy_http_version 	1.1;
proxy_set_header 	Upgrade $http_upgrade;
proxy_set_header 	Connection $connection_upgrade;
proxy_read_timeout	86400;
```

May be Mesos prevents a WS connection or somehow overrides one of those options to make it unstable. For example, as you see `close` is required once connection is closed, otherwise it won't work properly. More on this http://nginx.org/en/docs/http/websocket.html

**Comment by JordanFaust** [comment]
The connection can connect initially and several the different instances are created in the database assuming this is the first time the command has been ran since the server has been deployed. Things start failing after the agent has started and the API is ready as noted in the logs. At this time is when the connection starts failing. Investigating if this is firewall/iptables issue but so far nothing has shown up that would indicate this is the issue. Will post with more details shortly.

**Comment by roman-vynar** [comment]
The same issue happens if you replace
```
proxy_set_header    Connection $connection_upgrade;
```
with
```
proxy_set_header    Connection Upgrade;
```
It works but later fails, thus requires the mapping to `close` as mentioned above.

**Comment by JordanFaust** [comment]
The issue was related to proxy settings. Using the latest version of Mesos and Marathon LB should resolve the issue.
