### ISSUE TITLE
Agent cannot connect to API

### ISSUE THREAD

**Issue by adc-jglick** [percona/qan-agent#9]
I did a fresh install of the July 28th released code (both the server docker container).  The QAN is giving me two issues.

1. When loading the Percona Query Analytics web page, I get the following error:
QAN API error: "MySQL Query Analytics configuration not found".
Check the /var/log/qan-api.log file in docker container for more information.

The log file looks fine and the config file does exist.  Here is the complete qan-api.log:
`Percona Query Analytics API is running...
2016/08/03 22:03:20 config.go:79: Loading /usr/local/percona/qan-api/src/github.com/percona/qan-api/conf/prod.conf
2016/08/03 22:03:20 config.go:119: API root dir /usr/local/percona/qan-api/src/github.com/percona/qan-api
^[[0;32mINFO 2016/08/03 22:03:20 revel.go:206: Initialized Revel v0.12.0dev (2015-01-19) for >= go1.3
^[[0m^[[0;32mINFO 2016/08/03 22:03:20 main.go:31: Running revel server
^[[0mListening on 0.0.0.0:9001...
^[[0;32mINFO 2016/08/03 22:38:00 init.go:227: auth agent: not found: 714117adc57c403b74a46acf708620bc
^[[0m^[[0;32mINFO 2016/08/03 22:39:03 init.go:227: auth agent: not found: 714117adc57c403b74a46acf708620bc
^[[0m`

2. On the client host, I'm running version: pmm-client-1.0.2-x86_64

Here's what I'm seeing in the pmm-queries-exporter-42001.log:
`root@MySQL-Stage:/var/log# cat pmm-queries-exporter-42001.log 
2016/08/03 17:42:42.916174 WARNING data-sender Cannot connect to API:  bad status
2016/08/03 17:42:44.929117 WARNING agent-ws bad status
2016/08/03 17:42:44.931801 WARNING log-ws bad status
2016/08/03 17:42:45.922244 WARNING data-sender Cannot connect to API:  bad status
2016/08/03 17:42:46.939460 main.go:366: Caught interrupt signal, shutting down
2016/08/03 17:42:46.939555 main.go:392: Stopping QAN...
2016/08/03 17:42:46.939597 main.go:399: Waiting 2 seconds to flush agent log to API...
2016/08/03 17:42:48.928301 WARNING data-sender Cannot connect to API:  bad status
2016/08/03 17:42:48.939781 main.go:164: Agent has stopped
# Version: percona-qan-agent 1.0.0
# Basedir: /usr/local/percona/qan-agent
# Listen:  127.0.0.1:42001
# PID:     28963
# API:     pmm.host.test/qan-api
# UUID:    714117adc57c403b74a46acf708620bc
2016/08/03 17:44:34.260891 main.go:160: Starting agent...
2016/08/03 17:44:34.261911 main.go:338: Agent is ready
2016/08/03 17:44:34.275153 main.go:202: API is ready
2016/08/03 17:44:35.270150 WARNING agent-ws bad status
2016/08/03 17:44:35.271840 WARNING log-ws bad status
2016/08/03 17:44:38.277244 WARNING agent-ws bad status
2016/08/03 17:44:38.280705 WARNING log-ws bad status
2016/08/03 17:44:45.287988 WARNING agent-ws bad status
2016/08/03 17:44:45.293715 WARNING log-ws bad status`

All services are showing in consul (including queries)

**Comment by roman-vynar** [comment]
This should be fixed in the new releases. If you still have issues, please ask on our [forum](https://www.percona.com/forums/questions-discussions/percona-monitoring-and-management)
